<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8>
    <link rel="stylesheet" href="styles.css">
    <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>T-spa Fun n´ games</title>
</head>
<body>

<!-- Hi,
We are excited that you might join us at tobiigaming.com ! The fun is about to begin.

Please complete the following steps:
1) Create a grid with the images below.
2) Make it mobile first and responsive and check it in different browsers.
3) Each image needs to have a title and tags.
4) When a user hovers an image, fade in the title.
5) Add a client side search based on the tags.
6) Read the same data (image, title and tags) in a JSON format from PHP and show the same grid.

Reply us with the result in a zip file and how to run your code. Feel free to direct any questions. We will arrange for a meeting with you shortly after these steps, if needed.

-->


<!-- Grid based on html and css -->

<!--<article class="h33">
  <header>
    <p>hello world of gaming </p>
    <p>Inbox is an awesome new email client from the Gmail team. I’ve had the pleasure of test-driving this for a few months, and I have to say: It’s an incredibly well-polished app with a very smart set of features.</p>
    <p>It combines everything I like about Gmail, Mail.app, and Mailbox app, removes the features I don’t use, and absolutely shines as an example of Material Design.</p>
    <p>I also love the fact that Google’s not just positioning it as “The Next Gmail,” but rather as an all new product—and it looks like it will be supporting a variety of other email services as well.</p>
    <p>Really tremendous work and a huge congrats to all my colleagues that took part in shipping this.</p>
  </header>
</article>
-->
<section class="games_grid">
  <div class="grid_cell h33">
    <img src="assets/img/WD2_Thumb.jpg" title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/SteepThumbnail.jpg" title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/Games_Thumbnails_Division-1.jpg"  title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/ACSThumb169.png"  title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/ElitDangerousThumbnail.png"  title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/DX_thumb620.jpg"  title="Game-Title" class="fp shooter free new" >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/Games_Thumbnails_SolusProject169.jpg" title="Game-Title" class="fp shooter free new"  >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/FarmingSimulator_thumb.jpg" title="Game-Title" class="fp shooter free new"  >
  </div>
  <div class="grid_cell h33">
    <img src="assets/img/Pollen-capsule_main-featureimage.png"  title="Game-Title" class="fp shooter free new" >
  </div>
</section>







</body>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script type="text/javascript">
$('.grid_cell img').each(function() {
    cap = '<caption>'+ $(this).attr('title')+'</caption>';
    $(this).after( cap );
});
</script>

</html>
