<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8>
    <link rel="stylesheet" href="styles.css">
    <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>T-spa Fun n´ games - Populated from Json Array</title>
</head>
<body>

<!-- Hi,
We are excited that you might join us at tobiigaming.com ! The fun is about to begin.

Please complete the following steps:
1) Create a grid with the images below.
2) Make it mobile first and responsive and check it in different browsers.
3) Each image needs to have a title and tags.
4) When a user hovers an image, fade in the title.
5) Add a client side search based on the tags.
6) Read the same data (image, title and tags) in a JSON format from PHP and show the same grid.

Reply us with the result in a zip file and how to run your code. Feel free to direct any questions. We will arrange for a meeting with you shortly after these steps, if needed.

-->

<!-- Search -->
<section>
  <form name="searchfilter">
    <input id="search_input" type="text" name="search" placeholder="Search by tags, eg New, free, fp, shooter.. " class="awesomplete" data-list="fp, shooter, free, adventure, sneaker, platform, gravity, reality, space, immersive, 3d, new" /></input>
  </form>

</section>

<!-- Grid based on flexbox -->
<section id="games_container" class="games_grid">
<?php
    //Array could be fetched from endpoint url or db
    $gamesData = '[
        {"game":"Watch Dogs 2", "img":"WD2_Thumb.jpg", "tags":"fp shooter new"},
        {"game":"Steep", "img":"SteepThumbnail.jpg", "tags":"fp adventure new"},
        {"game":"The Division","img":"Games_Thumbnails_Division-1.jpg","tags":"fp shooter free"},
        {"game":"Assasins Creed","img":"ACSThumb169.png","tags":"fp sneaker free"},
        {"game":"Elite Dangerous","img":"ElitDangerousThumbnail.png","tags":"platform shooter free"},
        {"game":"Deus Ex","img":"ElitDangerousThumbnail.png","tags":"platform shooter new"},
        {"game":"Solus Project", "img":"Games_Thumbnails_SolusProject169.jpg", "tags":"gravity 3d space new"},
        {"game":"Farming Simulator","img":"FarmingSimulator_thumb.jpg", "tags":"fp reality immersive"},
        {"game":"Pollen","img":"Pollen-capsule_main-featureimage.png", "tags":"fp immersive new"}
      ]';

      // Loop it real good "true" sets array as opposed to object
      $gamesArr = json_decode($gamesData, true);
      foreach ($gamesArr as $key => $value) {
        echo '<div class="grid_cell">';
        echo '<img src="assets/img/'.$value["img"].'" title="' . $value["game"] . '" class="' . $value["tags"] . '">';
        echo '</div>';
      }
 ?>
</section>


</body>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="assets/vendor/awesomplete.js" async></script>
<script type="text/javascript">

// Create caption and tags from <img> attributes
$('.grid_cell img').each(function() {
    tags = '<span class="tag">'+ $(this).attr('class') + '</span>';
    cap = '<div class="caption">'+ $(this).attr('title') + tags +'</div>';
    $(this).after( cap );
});

$(document).ready(function(event) {
  // cancel form request for now
  $('form[name=searchfilter]').submit(function(event){
      event.preventDefault();
    });

  // Search/filter grid images based on their classes, todo: reset filtering
  $('input.awesomplete').on('awesomplete-selectcomplete',function(){
      tag_class = '.' + this.value
      $("img").not(tag_class).parent().fadeToggle("fast");
  });

});

</script>
</html>
