<html>
<head>
</head>
<body>

<!-- Hi,
We are excited that you might join us at tobiigaming.com ! The fun is about to begin.

Please complete the following steps:
1) Create a grid with the images below.
2) Make it mobile first and responsive and check it in different browsers.
3) Each image needs to have a title and tags.
4) When a user hovers an image, fade in the title.
5) Add a client side search based on the tags.
6) Read the same data (image, title and tags) in a JSON format from PHP and show the same grid.

Reply us with the result in a zip file and how to run your code. Feel free to direct any questions. We will arrange for a meeting with you shortly after these steps, if needed.

-->

<img src="https://tobiigaming.com/wp-content/uploads/2016/10/WD2_Thumb.jpg" title="Game-Title" class="fp shooter free new" >
<img src="https://tobiigaming.com/wp-content/uploads/2016/11/SteepThumbnail.jpg" title="Game-Title" class="fp shooter free new" >
<img src="https://tobiigaming.com/wp-content/uploads/2016/09/Games_Thumbnails_Division-1.jpg"  title="Game-Title" class="fp shooter free new" >
<img src="https://tobiigaming.com/wp-content/uploads/2016/09/ACSThumb169.png"  title="Game-Title" class="fp shooter free new" >

<img src="https://tobiigaming.com/wp-content/uploads/2016/09/ElitDangerousThumbnail.png"  title="Game-Title" class="fp shooter free new" >
<img src="https://tobiigaming.com/wp-content/uploads/2016/09/DX_thumb620.jpg"  title="Game-Title" class="fp shooter free new" >
<img src="https://tobiigaming.com/wp-content/uploads/2016/10/Games_Thumbnails_SolusProject169.jpg" title="Game-Title" class="fp shooter free new"  >
<img src="https://tobiigaming.com/wp-content/uploads/2016/09/FarmingSimulator_thumb.jpg" title="Game-Title" class="fp shooter free new"  >
<img src="https://tobiigaming.com/wp-content/uploads/2016/10/Pollen-capsule_main-featureimage.png"  title="Game-Title" class="fp shooter free new" >

</body>
</html>
